"""Generate the operations dashboard: a self-contained local HTML page.

Reads: data/candidates_today.json, logs/recorder.log, data/books/, the map and
findings docs. Writes: dashboard/index.html. Regenerated by the daily job; no
server, no external resources, nothing leaves the machine.
"""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

from ..core.paths import (
    BOOKS,
    CANDIDATES,
    CHECKPOINTS,
    DASHBOARD as OUT,
    EDGE_HISTORY,
    LOGS,
    RULEBOOK_VERDICTS,
    SHADOW_BOOK,
    STATE,
    TAIL_SIGNALS,
)

STYLE = """<style>
:root { --bg:#fcfcfb; --card:#fff; --ink:#0b0b0b; --ink2:#52514e; --mut:#898781; --line:#e1e0d9; --acc:#2a78d6; }
@media (prefers-color-scheme: dark) { :root { --bg:#0d0d0d; --card:#1a1a19; --ink:#fff; --ink2:#c3c2b7; --mut:#898781; --line:#2c2c2a; --acc:#3987e5; } }
* { box-sizing:border-box; margin:0; }
body { background:var(--bg); color:var(--ink); font:15px/1.6 -apple-system,'Segoe UI',sans-serif; padding:24px; max-width:1100px; margin:0 auto; }
h1 { font-size:20px; font-weight:600; } h2 { font-size:15px; font-weight:600; margin:28px 0 10px; color:var(--ink); }
.sub { color:var(--mut); font-size:13px; margin-bottom:20px; }
.tiles { display:grid; grid-template-columns:repeat(auto-fit,minmax(160px,1fr)); gap:10px; }
.tile { background:var(--card); border:1px solid var(--line); border-radius:10px; padding:12px 14px; }
.tile .v { font-size:22px; font-weight:600; } .tile .l { font-size:12px; color:var(--mut); }
table { width:100%; border-collapse:collapse; background:var(--card); border:1px solid var(--line); border-radius:10px; overflow:hidden; font-size:13px; }
th { text-align:left; color:var(--mut); font-weight:500; padding:8px 10px; border-bottom:1px solid var(--line); }
td { padding:7px 10px; border-bottom:1px solid var(--line); color:var(--ink2); }
tr:last-child td { border-bottom:none; }
.mono { font-family:ui-monospace,monospace; font-size:12px; color:var(--ink); }
.num { text-align:right; font-variant-numeric:tabular-nums; }
.chip { display:inline-block; font-size:11px; font-weight:600; color:var(--c); border:1px solid var(--c); border-radius:20px; padding:0 8px; }
.cell { background:var(--card); border:1px solid var(--line); border-left:3px solid var(--acc); border-radius:0 10px 10px 0; padding:10px 14px; margin-bottom:8px; }
.cellname { font-weight:600; } .cellstats { font-size:13px; color:var(--ink2); }
.role { font-size:11px; color:var(--mut); font-weight:500; margin-left:6px; }
ul { padding-left:20px; color:var(--ink2); font-size:14px; } li { margin:4px 0; }
.who { color:var(--mut); font-size:12px; }
.warn { background:var(--card); border:1px solid var(--line); border-radius:10px; padding:10px 14px; color:var(--ink2); font-size:13px; margin-top:8px; }
details summary { cursor:pointer; color:var(--mut); font-size:13px; }
</style>"""


NAV = (
    "<div style='margin-bottom:12px; font-size:14px;'>"
    "<a href='index.html' style='color:var(--acc); text-decoration:none; margin-right:16px;'>Overview</a>"
    "<a href='congress.html' style='color:var(--acc); text-decoration:none;'>Congress — confirmation pipeline research</a>"
    "</div>"
)

CELLS = [
    {"name": "Politics · T−30d · YES 1–5¢", "disc": "+30.4%", "conf": "+28.7%",
     "bound": "+21.7%", "capacity": "$5.0M / 617 mkts", "role": "primary"},
    {"name": "Financials · T−90d · YES 1–10¢ (ex-ticket)", "disc": "+17.9%", "conf": "+16.8%",
     "bound": "+11.1%", "capacity": "$12.4M / 1,258 mkts", "role": "secondary"},
]

FINDINGS = [
    ("F1", "Long-dated YES overpriced everywhere; NO collects"),
    ("F2", "Published favorite edge dead; longshot side survives"),
    ("F3", "Sign flips at pro-priced series — selection mandatory"),
    ("F4", "Makers beat takers everywhere (+8 to +31pp/fill)"),
    ("F5", "No term premium — edge peaks at 30–90d, recycle"),
    ("F6", "Insurance-shaped returns; edge is a portfolio property"),
    ("F7", "Capacity, not edge, is the constraint"),
    ("F8", "Bracket 'free money' is almost always a trap"),
    ("F9", "Fees/carry verified; escrow question open"),
]


def recorder_status() -> tuple[str, str]:
    log = LOGS / "recorder.log"
    last = log.read_text().strip().splitlines()[-1] if log.exists() else "no runs yet"
    books = sorted(BOOKS.glob("books_*.jsonl"))
    day_files = len(books)
    return last, f"{day_files} day-files"


def deployment_status() -> str:
    """Summarize actual portfolio state instead of duplicating a stale phase label."""
    pf = STATE / "portfolio.json"
    if not pf.exists():
        return "portfolio sync not yet run"
    portfolio = json.loads(pf.read_text())
    if not portfolio.get("available"):
        return "portfolio not connected"
    positions = len(portfolio.get("positions", []))
    orders = len(portfolio.get("resting_orders", []))
    if positions and orders:
        return f"{positions} live positions · {orders} resting orders"
    if positions:
        return f"{positions} live positions · no resting orders"
    if orders:
        return f"{orders} live orders resting — no filled positions"
    return "no live orders or positions"


def chip(verdict: str, tooltip: str = "") -> str:
    color = {"GREEN": "#0a7a33", "YELLOW": "#9a6b00", "AMBER": "#9a6b00",
             "UNSWEPT": "#666", "THIN": "#666", "RED": "#b3261e",
             "CLEAR": "#0a7a33", "WARM": "#9a6b00", "HOT": "#b3261e", "UNKNOWN": "#666"}[verdict]
    t = f' title="{tooltip}"' if tooltip else ""
    return f'<span class="chip" style="--c:{color}"{t}>{verdict}</span>'


def health_checks() -> list[tuple[str, bool, str]]:
    """Step 0: the four freshness gates. (name, ok, detail)."""
    now = dt.datetime.now(dt.timezone.utc)
    checks = []

    todays_books = BOOKS / f"books_{now:%Y%m%d}.jsonl"
    yesterdays = BOOKS / f"books_{(now - dt.timedelta(days=1)):%Y%m%d}.jsonl"
    ok = todays_books.exists() or (now.hour < 8 and yesterdays.exists())
    detail = "today's file present" if todays_books.exists() else "no snapshot yet today"
    checks.append(("recorder", ok, detail))

    ckpt = CHECKPOINTS / "incremental.json"
    if ckpt.exists():
        hw = dt.datetime.fromisoformat(json.loads(ckpt.read_text())["high_water"])
        age_h = (now - hw).total_seconds() / 3600
        checks.append(("settled ingest", age_h < 36, f"high water {age_h:.0f}h ago"))
    else:
        checks.append(("settled ingest", False, "never run"))

    cands = CANDIDATES
    if cands.exists():
        age_h = (now - dt.datetime.fromtimestamp(cands.stat().st_mtime, dt.timezone.utc)).total_seconds() / 3600
        checks.append(("candidates", age_h < 30, f"refreshed {age_h:.0f}h ago"))
    else:
        checks.append(("candidates", False, "never run"))

    hist = EDGE_HISTORY
    if hist.exists():
        last = json.loads(hist.read_text().strip().splitlines()[-1])
        age_d = (now - dt.datetime.fromisoformat(last["ts"])).days
        checks.append(("edge grading", age_d <= 8, f"graded {age_d}d ago"))
    else:
        checks.append(("edge grading", False, "never run"))

    ops = STATE / "ops_status.json"
    if ops.exists():
        rec = json.loads(ops.read_text())
        age_h = (now - dt.datetime.fromisoformat(rec["ts"])).total_seconds() / 3600
        checks.append(("ops pass", age_h < 30, f"{rec.get('status', '?')}, {age_h:.0f}h ago"))
    else:
        checks.append(("ops pass", False, "never run"))
    return checks


def alert_banner_html() -> str:
    ops = STATE / "ops_status.json"
    if not ops.exists():
        return ""
    rec = json.loads(ops.read_text())
    if rec.get("status") != "alerts" or not rec.get("alerts"):
        return ""
    items = "".join(f"<li>{a}</li>" for a in rec["alerts"])
    return (
        "<div style='background:#b3261e; color:#fff; border-radius:10px; padding:12px 16px; "
        "margin-bottom:14px; font-size:14px;'><b>OPERATOR ALERTS — needs you</b>"
        f"<ul style='margin:6px 0 0 18px'>{items}</ul></div>"
    )


def health_strip_html() -> str:
    items = []
    all_ok = True
    for name, ok, detail in health_checks():
        all_ok &= ok
        mark = "✓" if ok else "✗"
        color = "#0a7a33" if ok else "#b3261e"
        items.append(
            f"<span style='margin-right:18px'><b style='color:{color}'>{mark}</b> "
            f"{name} <span style='color:var(--mut); font-size:12px'>({detail})</span></span>"
        )
    verdict = (
        "<b style='color:#0a7a33'>SYSTEM HEALTHY — proceed to step 1</b>" if all_ok
        else "<b style='color:#b3261e'>STALE DATA — fix the pipeline before any trading decision</b>"
    )
    return (
        f"<div style='background:var(--card); border:1px solid var(--line); border-radius:10px; "
        f"padding:10px 14px; margin-bottom:14px; font-size:13px;'>"
        f"<div style='color:var(--mut); font-size:12px; margin-bottom:4px'>step 0 — machine health</div>"
        f"{''.join(items)}<div style='margin-top:6px'>{verdict}</div></div>"
    )


def real_book_html() -> str:
    pf = STATE / "portfolio.json"
    if not pf.exists():
        return "<p class='sub'>real portfolio: sync never run</p>"
    p = json.loads(pf.read_text())
    if not p.get("available"):
        return (
            "<div class='warn'><b>Real portfolio: not connected.</b> "
            "Create a Kalshi API key (account settings), then place the two files yourself: "
            "<span class='mono'>~/.kalshi/key_id</span> and <span class='mono'>~/.kalshi/kalshi.pem</span> "
            "(chmod 600). The sync is read-only by construction; the key never enters this repo or any chat.</div>"
        )
    s = p["sizing"]
    tiles = (
        f"<div class='tiles' style='margin-bottom:10px'>"
        f"<div class='tile'><div class='v'>${p['equity_usd']:,.2f}</div><div class='l'>equity (cash ${p['cash_usd']:,.2f} + positions ${p['exposure_usd']:,.2f})</div></div>"
        f"<div class='tile'><div class='v'>${p['pnl_usd']:+,.2f}</div><div class='l'>P&L since {p['since']} (baseline ${p['baseline_usd']:,.2f})</div></div>"
        f"<div class='tile'><div class='v'>${s['politics_unit_usd']:,.0f} / ${s['financials_unit_usd']:,.0f}</div><div class='l'>live unit: Politics / Financials (2.5% of equity, AMBER ×½)</div></div>"
        f"<div class='tile'><div class='v'>{len(p['positions'])} + {len(p['resting_orders'])}</div><div class='l'>positions + resting orders</div></div>"
        f"</div>"
    )
    rows = "".join(
        f"<tr><td class='mono'>{r['ticker']}</td><td>{r['side']}</td>"
        f"<td class='num'>{abs(r['position'])}</td><td class='num'>${r['exposure_usd']:,.2f}</td>"
        f"<td class='num'>${r['realized_usd']:+,.2f}</td></tr>"
        for r in p["positions"]
    )
    orders = "".join(
        f"<tr><td class='mono'>{r['ticker']}</td><td>{r['side']}</td>"
        f"<td class='num'>{r['price_c']}¢</td><td class='num'>{r['resting']}</td></tr>"
        for r in p["resting_orders"]
    )
    html = tiles
    if rows:
        html += ("<table><tr><th>position</th><th>side</th><th>qty</th><th>value</th><th>realized</th></tr>"
                 + rows + "</table>")
    if orders:
        html += ("<div style='height:8px'></div><table><tr><th>resting order</th><th>side</th><th>price</th><th>qty</th></tr>"
                 + orders + "</table>")
    if not rows and not orders:
        html += "<div class='sub'>no positions or resting orders yet — cash earning APY</div>"
    return html + f"<div class='sub' style='margin-top:6px'>read-only sync · updated {p['ts'][:16]}</div>"


def shadow_book_html() -> str:
    bf = SHADOW_BOOK
    if not bf.exists():
        return "<p class='sub'>shadow book: not yet started</p>"
    book = json.loads(bf.read_text())
    s = book.get("stats", {})
    tiles = (
        f"<div class='tiles' style='margin-bottom:10px'>"
        f"<div class='tile'><div class='v'>${s.get('deployed_usd',0):,.0f}</div><div class='l'>filled (paper), {s.get('deployed_pct',0)}% of book</div></div>"
        f"<div class='tile'><div class='v'>${s.get('resting_usd',0):,.0f}</div><div class='l'>resting unfilled</div></div>"
        f"<div class='tile'><div class='v'>${s.get('realized_usd',0):+,.2f}</div><div class='l'>realized P&L</div></div>"
        f"<div class='tile'><div class='v'>${s.get('unrealized_usd',0):+,.2f}</div><div class='l'>unrealized at mark</div></div>"
        f"</div>"
    )
    state_order = {"filled": 0, "partial": 1, "resting": 2, "settled": 3, "cancelled": 4}
    rows = []
    for o in sorted(book["orders"], key=lambda x: (state_order.get(x["state"], 9), x["ticker"])):
        fill = f"{o['filled_qty']}/{o['qty']}"
        pnl = ""
        if o["state"] == "settled":
            pnl = f"{o['realized_usd']:+,.2f} ({o['result']})"
        elif o["filled_qty"] and o.get("mark_c") is not None:
            pnl = f"{o['filled_qty'] * (o['mark_c'] - o['price_c']) / 100:+,.2f} @ mark {o['mark_c']}¢"
        committed = o["qty"] * o["price_c"] / 100
        rows.append(
            f"<tr><td class='mono'>{o['ticker']}</td><td>{o['title'][:44]}</td>"
            f"<td class='num'>{o['price_c']}¢</td><td class='num'>{fill}</td>"
            f"<td class='num'>${committed:,.0f}</td>"
            f"<td>{o['state']}</td><td class='num'>{pnl}</td></tr>"
        )
    table = (
        "<table><tr><th>ticker</th><th>market</th><th>rest NO</th><th>filled</th><th>size</th><th>state</th><th>P&L</th></tr>"
        + "".join(rows) + "</table>"
    )
    sizing = (
        "<div class='sub' style='margin:6px 0'>sizing: $10,000 paper book · $250/position Politics (GREEN light) · "
        "$125/position Financials (AMBER = ×½) · one position per event · max loss per position = its size</div>"
    )
    table = sizing + table
    note = (
        "<div class='sub' style='margin-top:6px'>PAPER ONLY — fills simulated as 50% of real prints at/through "
        "our price (queue unknown); settlements and P&L are real outcomes. Started "
        f"{book['created'][:10]}, updated {book.get('updated','—')[:16]}.</div>"
    )
    return tiles + table + note


def congress_page(style: str, now: str) -> str:
    """The congressional watcher's research surface: live evidence per market."""
    tails = json.loads(TAIL_SIGNALS.read_text()) if TAIL_SIGNALS.exists() else []
    held = set()
    if SHADOW_BOOK.exists():
        book = json.loads(SHADOW_BOOK.read_text())
        held = {o["ticker"] for o in book.get("orders", []) if o["state"] not in ("cancelled", "settled")}

    rows = "".join(
        f"<tr><td class='mono'>{t['ticker']}</td><td>{t.get('nominee') or '—'}</td>"
        f"<td>{chip(t['signal'])}</td>"
        f"<td>{'YES' if t['ticker'] in held else ''}</td>"
        f"<td>{t['evidence']}</td>"
        f"<td class='num'>{t.get('session_days_left') if t.get('session_days_left') is not None else '?'}</td>"
        f"<td class='num'>{t['checked'][:16]}</td></tr>"
        for t in tails
    ) or "<tr><td colspan='7'>no confirmation-type candidates in today's window</td></tr>"

    return f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Kalshi structure — Congress</title>{style}</head><body>
<h1>Congress — confirmation pipeline research</h1>
<div class="sub">generated {now} · a nominee cannot be confirmed without published floor time —
this page shows what the watcher found for every confirmation-type candidate market</div>
{NAV}
<h2>Method</h2>
<div class="warn">Daily: fetch the <a href='https://www.senate.gov/legislative/LIS/executive_calendar/xcalv.pdf'
style='color:var(--acc)'>Senate Executive Calendar</a> (official PDF), extract each market's nominee from its
title, and search the calendar. Absent → CLEAR (still in committee; calendaring would be caught next run).
Present → WARM (floor-eligible any session day). In the cloture section → HOT (vote imminent; never place,
flag held positions). Extraction failure → UNKNOWN, treated as WARM, never CLEAR. Session-days column is
'?' until the congress.gov API key provides the forward floor schedule.</div>

<h2>Current signals</h2>
<table><tr><th>market</th><th>nominee</th><th>signal</th><th>held?</th>
<th>evidence — literal text from the calendar</th><th>session days</th><th>checked</th></tr>
{rows}</table>

<div class="sub" style="margin-top:8px">History: <span class='mono'>reports/tail_signals.md</span> ·
signals also chip the Overview candidate rows · placement rule: HOT is never placed</div>
</body></html>"""


def edge_health_html() -> str:
    hist = EDGE_HISTORY
    if not hist.exists():
        return "<p class='sub'>edge health: not yet run</p>"
    rec = json.loads(hist.read_text().strip().splitlines()[-1])
    rows = []
    for name, e in rec["cells"].items():
        t90 = e["t90"]
        stat = (
            f"trailing-90d {t90['mean']:+.1%} ± {t90['se']:.1%} (n={t90['n']}) · baseline {e['baseline']:+.1%}"
            if t90.get("mean") is not None else f"insufficient sample (n={t90.get('n', 0)})"
        )
        rows.append(
            f"<div class='cell'><div class='cellname'>{name} {chip(e['light'])}</div>"
            f"<div class='cellstats'>{stat}</div></div>"
        )
    extras = (
        f"<div class='sub'>falsification metrics (trailing 90d): calibration gap "
        f"{rec.get('calibration_gap_t90')} · maker−taker gap {rec.get('maker_taker_gap_t90')} "
        f"over {rec.get('n_fills_t90', 0):,} fills · graded {rec['ts'][:10]}</div>"
    )
    return "".join(rows) + extras


def run() -> Path:
    cands = json.loads((CANDIDATES).read_text())
    rec_last, rec_days = recorder_status()
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    by_verdict = {}
    for c in cands:
        by_verdict[c["rulebook"]] = by_verdict.get(c["rulebook"], 0) + 1

    verdicts = json.loads(RULEBOOK_VERDICTS.read_text()) if RULEBOOK_VERDICTS.exists() else {}
    tail_ev = {}
    if TAIL_SIGNALS.exists():
        tail_ev = {t["ticker"]: t["evidence"] for t in json.loads(TAIL_SIGNALS.read_text())}

    def cand_rows(cat):
        rows = [c for c in cands if c["category"] == cat]
        rows.sort(key=lambda c: int(c["days_to_close"]))
        out = []
        for c in rows:
            url = f"https://kalshi.com/markets/{c['series'].lower()}"
            out.append(
                f"<tr><td class='mono'><a href='{url}' style='color:var(--acc); text-decoration:none'>{c['ticker']}</a></td><td>{c['title']}</td>"
                f"<td class='num'>{c['days_to_close']}</td><td class='num'>{c['yes_ask_c']}¢</td>"
                f"<td class='num'>{c['rest_no_at_c']}¢</td><td>{chip(c['rulebook'], verdicts.get(c['series'], {}).get('reason', ''))}"
                + (f" {chip(c['tail_signal'], tail_ev.get(c['ticker'], ''))}" if c.get("tail_signal") else "")
                + "</td></tr>"
            )
        return "\n".join(out), len(rows)

    pol_rows, pol_n = cand_rows("Politics")
    fin_rows, fin_n = cand_rows("Financials")

    cells_html = "".join(
        f"<div class='cell'><div class='cellname'>{c['name']} <span class='role'>{c['role']}</span></div>"
        f"<div class='cellstats'>discovery {c['disc']}/yr · confirmation {c['conf']}/yr · "
        f"conservative bound {c['bound']}/yr · capacity {c['capacity']}</div></div>"
        for c in CELLS
    )
    findings_html = "".join(f"<li><b>{k}</b> {v}</li>" for k, v in FINDINGS)

    html = f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Kalshi structure — operations dashboard</title>
{STYLE}</head><body>
<h1>Kalshi market structure — operations</h1>
<div class="sub">generated {now} · data through latest settled feed · recorder: {rec_days} · deployment status: <b>{deployment_status()}</b></div>
{NAV}

{alert_banner_html()}{health_strip_html()}

<div class="tiles">
  <div class="tile"><div class="v">2</div><div class="l">qualifying cells (of 58)</div></div>
  <div class="tile"><div class="v">{len(cands)}</div><div class="l">candidates today</div></div>
  <div class="tile"><div class="v">{by_verdict.get('GREEN',0)} / {by_verdict.get('YELLOW',0)} / {by_verdict.get('UNSWEPT',0)}</div><div class="l">green / yellow / unswept</div></div>
  <div class="tile"><div class="v">1-in-10</div><div class="l">expected tail loss rate</div></div>
  <div class="tile"><div class="v">~15%/yr</div><div class="l">politics cell, pessimistic tail</div></div>
</div>

<h2>Real portfolio — your Kalshi account (read-only)</h2>
{real_book_html()}

<h2>Shadow book — paper control group ($10k nominal)</h2>
{shadow_book_html()}

<h2>Edge health (weekly, pre-committed lights: AMBER = halve entries, RED = stop)</h2>
{edge_health_html()}

<h2>Qualifying cells (Phase 3 map, 2026-07-16)</h2>
{cells_html}

<h2>Today's candidates — Politics ({pol_n}) <span class="who">rest NO at 100 − ask · UNSWEPT = do not touch until rules read</span></h2>
<table><tr><th>ticker</th><th>market</th><th>days</th><th>YES ask</th><th>rest NO at</th><th>rulebook</th></tr>
{pol_rows}</table>

<h2>Today's candidates — Financials ({fin_n})</h2>
<table><tr><th>ticker</th><th>market</th><th>days</th><th>YES ask</th><th>rest NO at</th><th>rulebook</th></tr>
{fin_rows}</table>

<h2>Validated findings (details in market-structure.md)</h2>
<ul>{findings_html}</ul>

<div class="warn">This dashboard reports research output, not advice. Qualification: 7%/yr at 2 clustered SE
in both periods. Tail estimates rest on 1 observed loss per cell — see memos. Recorder last run: {rec_last}</div>
</body></html>"""
    OUT.mkdir(exist_ok=True)
    (OUT / "congress.html").write_text(congress_page(STYLE, now))
    path = OUT / "index.html"
    path.write_text(html)
    print(f"dashboard -> {path}")
    return path


if __name__ == "__main__":
    run()
