"""Generate the operations dashboard: a self-contained local HTML page.

Reads: data/candidates_today.json, logs/recorder.log, data/books/, the map and
findings docs. Writes: dashboard/index.html. Regenerated by the daily job; no
server, no external resources, nothing leaves the machine.
"""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "data"
OUT = ROOT / "dashboard"

CELLS = [
    {"name": "Politics · T−30d · YES 1–5¢", "disc": "+30.4%", "conf": "+28.7%",
     "bound": "+21.7%", "capacity": "$5.0M / 617 mkts", "role": "primary"},
    {"name": "Financials · T−90d · YES 1–10¢ (ex-ticket)", "disc": "+17.9%", "conf": "+16.8%",
     "bound": "+11.1%", "capacity": "$12.4M / 1,258 mkts", "role": "secondary"},
]

OPEN_ITEMS = [
    ("Escrow-carry support ticket", "user", "does resting-order collateral earn APY?"),
    ("Regulatory posture read — political event contracts", "user", "before first dollars"),
    ("Rulebook sweep of today's UNSWEPT candidates", "agent", "rolling daily chore"),
    ("Screen C scanner on daily schedule", "agent", "two-week arb census"),
    ("Forward-validation weekly job", "agent", "falsification tracker"),
]

FINDINGS = [
    ("F1", "Long-dated YES overpriced everywhere; NO collects"),
    ("F2", "Published favorite edge dead; longshot side survives"),
    ("F3", "Sign flips at pro-priced series — selection mandatory"),
    ("F4", "Makers beat takers everywhere (+8 to +31pp/fill)"),
    ("F5", "No term premium — edge peaks at 30–90d, recycle"),
    ("F6", "Insurance-shaped returns; edge is a portfolio property"),
    ("F7", "Capacity, not edge, is the constraint"),
    ("F8", "Bracket 'free money' is almost always a trap"),
    ("F9", "Fees/carry verified; escrow question open"),
]


def recorder_status() -> tuple[str, str]:
    log = ROOT / "logs" / "recorder.log"
    last = log.read_text().strip().splitlines()[-1] if log.exists() else "no runs yet"
    books = sorted((DATA / "books").glob("books_*.jsonl"))
    day_files = len(books)
    return last, f"{day_files} day-files"


def chip(verdict: str) -> str:
    color = {"GREEN": "#0a7a33", "YELLOW": "#9a6b00", "UNSWEPT": "#666", "RED": "#b3261e"}[verdict]
    return f'<span class="chip" style="--c:{color}">{verdict}</span>'


def run() -> Path:
    cands = json.loads((DATA / "candidates_today.json").read_text())
    rec_last, rec_days = recorder_status()
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    by_verdict = {}
    for c in cands:
        by_verdict[c["rulebook"]] = by_verdict.get(c["rulebook"], 0) + 1

    def cand_rows(cat):
        rows = [c for c in cands if c["category"] == cat]
        rows.sort(key=lambda c: int(c["days_to_close"]))
        out = []
        for c in rows:
            out.append(
                f"<tr><td class='mono'>{c['ticker']}</td><td>{c['title']}</td>"
                f"<td class='num'>{c['days_to_close']}</td><td class='num'>{c['yes_ask_c']}¢</td>"
                f"<td class='num'>{c['rest_no_at_c']}¢</td><td>{chip(c['rulebook'])}</td></tr>"
            )
        return "\n".join(out), len(rows)

    pol_rows, pol_n = cand_rows("Politics")
    fin_rows, fin_n = cand_rows("Financials")

    cells_html = "".join(
        f"<div class='cell'><div class='cellname'>{c['name']} <span class='role'>{c['role']}</span></div>"
        f"<div class='cellstats'>discovery {c['disc']}/yr · confirmation {c['conf']}/yr · "
        f"conservative bound {c['bound']}/yr · capacity {c['capacity']}</div></div>"
        for c in CELLS
    )
    items_html = "".join(
        f"<li><b>{t}</b> <span class='who'>[{who}]</span> — {note}</li>" for t, who, note in OPEN_ITEMS
    )
    findings_html = "".join(f"<li><b>{k}</b> {v}</li>" for k, v in FINDINGS)

    html = f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Kalshi structure — operations dashboard</title>
<style>
:root {{ --bg:#fcfcfb; --card:#fff; --ink:#0b0b0b; --ink2:#52514e; --mut:#898781; --line:#e1e0d9; --acc:#2a78d6; }}
@media (prefers-color-scheme: dark) {{ :root {{ --bg:#0d0d0d; --card:#1a1a19; --ink:#fff; --ink2:#c3c2b7; --mut:#898781; --line:#2c2c2a; --acc:#3987e5; }} }}
* {{ box-sizing:border-box; margin:0; }}
body {{ background:var(--bg); color:var(--ink); font:15px/1.6 -apple-system,'Segoe UI',sans-serif; padding:24px; max-width:1100px; margin:0 auto; }}
h1 {{ font-size:20px; font-weight:600; }} h2 {{ font-size:15px; font-weight:600; margin:28px 0 10px; color:var(--ink); }}
.sub {{ color:var(--mut); font-size:13px; margin-bottom:20px; }}
.tiles {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(160px,1fr)); gap:10px; }}
.tile {{ background:var(--card); border:1px solid var(--line); border-radius:10px; padding:12px 14px; }}
.tile .v {{ font-size:22px; font-weight:600; }} .tile .l {{ font-size:12px; color:var(--mut); }}
table {{ width:100%; border-collapse:collapse; background:var(--card); border:1px solid var(--line); border-radius:10px; overflow:hidden; font-size:13px; }}
th {{ text-align:left; color:var(--mut); font-weight:500; padding:8px 10px; border-bottom:1px solid var(--line); }}
td {{ padding:7px 10px; border-bottom:1px solid var(--line); color:var(--ink2); }}
tr:last-child td {{ border-bottom:none; }}
.mono {{ font-family:ui-monospace,monospace; font-size:12px; color:var(--ink); }}
.num {{ text-align:right; font-variant-numeric:tabular-nums; }}
.chip {{ display:inline-block; font-size:11px; font-weight:600; color:var(--c); border:1px solid var(--c); border-radius:20px; padding:0 8px; }}
.cell {{ background:var(--card); border:1px solid var(--line); border-left:3px solid var(--acc); border-radius:0 10px 10px 0; padding:10px 14px; margin-bottom:8px; }}
.cellname {{ font-weight:600; }} .cellstats {{ font-size:13px; color:var(--ink2); }}
.role {{ font-size:11px; color:var(--mut); font-weight:500; margin-left:6px; }}
ul {{ padding-left:20px; color:var(--ink2); font-size:14px; }} li {{ margin:4px 0; }}
.who {{ color:var(--mut); font-size:12px; }}
.warn {{ background:var(--card); border:1px solid var(--line); border-radius:10px; padding:10px 14px; color:var(--ink2); font-size:13px; margin-top:8px; }}
details summary {{ cursor:pointer; color:var(--mut); font-size:13px; }}
</style></head><body>
<h1>Kalshi market structure — operations</h1>
<div class="sub">generated {now} · data through latest settled feed · recorder: {rec_days} · deployment status: <b>diligence phase — no live positions</b></div>

<div class="tiles">
  <div class="tile"><div class="v">2</div><div class="l">qualifying cells (of 58)</div></div>
  <div class="tile"><div class="v">{len(cands)}</div><div class="l">candidates today</div></div>
  <div class="tile"><div class="v">{by_verdict.get('GREEN',0)} / {by_verdict.get('YELLOW',0)} / {by_verdict.get('UNSWEPT',0)}</div><div class="l">green / yellow / unswept</div></div>
  <div class="tile"><div class="v">1-in-10</div><div class="l">expected tail loss rate</div></div>
  <div class="tile"><div class="v">~15%/yr</div><div class="l">politics cell, pessimistic tail</div></div>
</div>

<h2>Qualifying cells (Phase 3 map, 2026-07-16)</h2>
{cells_html}

<h2>Today's candidates — Politics ({pol_n}) <span class="who">rest NO at 100 − ask · UNSWEPT = do not touch until rules read</span></h2>
<table><tr><th>ticker</th><th>market</th><th>days</th><th>YES ask</th><th>rest NO at</th><th>rulebook</th></tr>
{pol_rows}</table>

<h2>Today's candidates — Financials ({fin_n})</h2>
<table><tr><th>ticker</th><th>market</th><th>days</th><th>YES ask</th><th>rest NO at</th><th>rulebook</th></tr>
{fin_rows}</table>

<h2>Open items before deployment</h2>
<ul>{items_html}</ul>

<h2>Validated findings (details in market-structure.md)</h2>
<ul>{findings_html}</ul>

<div class="warn">This dashboard reports research output, not advice. Qualification: 7%/yr at 2 clustered SE
in both periods. Tail estimates rest on 1 observed loss per cell — see memos. Recorder last run: {rec_last}</div>
</body></html>"""
    OUT.mkdir(exist_ok=True)
    path = OUT / "index.html"
    path.write_text(html)
    print(f"dashboard -> {path}")
    return path


if __name__ == "__main__":
    run()
